services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - APP_PORT=8080
      - DATABASE_URL=postgres://user:password@db:5432/dbname
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname
    ports:
      - "5432:5432"
